config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  devise_for :users, controllers: { registrations: "registrations"}
  get 'posts/favorite_ranking'
  resources :posts do
    resources :comments
  end
  
  resources :users, only: [:show]
  resources :favorites, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    validates :opinion, presence: true
    validates :user_id , presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true, length: {maximum:200}}
    validates :matter, {presence: true, length: {maximum:200}}
    validates :episode, {presence: true, length: {maximum:200}}
    validates :user_id, {presence: true}
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable       
         
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 200 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :age, numericality: true, allow_blank: true
  validates :town,length: { maximum: 30 }
  validates :introduce, presence: true, length: { maximum: 200 }
        
  before_validation { email.downcase! }
    
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger
  
  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password,:password_confirmation, :town, :age, :gender, :introduce, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password,:password_confirmation, :town, :age, :gender, :introduce, :image])
  end
  
  private
  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
    
  def new
    @comment = Comment.new
  end
    
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    end
  end
    
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end
    
  private
    
  def set_post
    @post = Post.find(params[:post_id])
  end
    
  def comment_params
    params.require(:comment).permit(:opinion, :post_id, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
    
  def create
    @favorite = current_user.favorites.create(post_id: params[:post_id])
    favorites_count
    redirect_to posts_url
  end
    
  def destroy
    set_favorite
    @favorite.destroy
    @favorite = nil
    favorites_count
    redirect_to posts_url
  end
    
  private
    
  def set_post
    @post = Post.find(params[:post_id])
  end
    
  def set_favorite
    @favorite = current_user.favorites.find_by(post_id: params[:post_id])
  end
    
  def favorites_count
    @favorites_count = Favorite.where(post_id: @post.id).count
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @post = Post.find_by(id: params[:id])
    @posts = Post.page(params[:page]).per(10)
    @favorite_ranking = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end
  
  def favorite_ranking
    @posts = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @favorite = current_user.favorites.find_by(post_id: @post.id) if user_signed_in?
    @favorites_count = Favorite.where(post_id: @post.id).count
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
     flash[:notice] = "投稿を作成しました"
     redirect_to @post
    else
     render :new
    end
    
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    
    if @post.update(post_params)
      flash[:notice] = "投稿を編集しました"
      redirect_to post_path
    else
      render :edit
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    
    redirect_to posts_path
  end
  
  def correct_user
    @user = User.find(Post.find(params[:id]).user_id)
    @current_user = current_user
    redirect_to posts_path, notice: '他のユーザーの投稿は編集できません。' unless view_context.current_user?(@user, @current_user)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:company, :industry, :content, :matter, :period, :episode)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  def after_update_path_for(resource)
    user_path(@user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    if params[:format].present?
      @user = User.find(params[:format])
    else
      @user = User.find(params[:id])
    end
    @posts = @user.posts
    @favorite_posts = Post.find(Favorite.find(@user.favorites.ids).pluck(:post_id))
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user?(user, current_user)
        user == current_user
    end
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-10">
      <%= form.text_area :opinion, :placeholder => '質問等を気軽にコメントをしてみましょう！', class:'form-control' %>
    </div>
    <div class="actions col-md-2">
      <input type="submit" value="コメントする">
    </div>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% unless comments.present? %>
  <h>コメントはまだありません。気軽にコメントしてみましょう！</p>
<% end %>
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="card one-comment">
      <div class="card-body comment-space">
        <p class="comment-name">
          <% if comment.user.image.present? %>
            <%= link_to user_path(comment.user.id), style: "background: transparent" do %>
              <%= image_tag comment.user.image,:size =>'60x60'%>
            <% end %>
          <% else %>
            <%= link_to user_path(comment.user.id), style: "background: transparent" do %>
              <%= image_tag '/user.png',:size =>'60x60' %>
            <% end %>
          <% end %>
          <%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %>
        </p>
        <div>
          <%= comment.opinion %>
          <% if comment.user == current_user %>
            <p class="comment-delete"><%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true do %>
              <i class="fa fa-trash fa-fw"></i> 削除
            <% end %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, blog: @comment.post }) %>")
$("textarea").val('')

app/views/favorites/_index.html.erb
<% if user_signed_in? %>
  <% unless @post.user_id == current_user.id %>
    <% if @favorite.present? %>
      <div class="fav-now floats">
        <%= link_to favorite_path(post_id: @post.id, id: @favorite.id), method: :delete, remote: true do %>
        お気に入りから外す
          <i class="fa fa-star fa-2x fav-now notfavorite-btn"></i>
        <% end %>
      </div>
    <% else %>
      <div class="fav-not floats">
        <%= link_to favorites_path(post_id: @post.id), method: :post, remote: true do %>
        お気に入りに登録する
          <i class="fa fa-star favorite-btn"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>
お気に入り！<%= @favorites_count %>件

app/views/favorites/index.js.erb
$("#favorite_area").html("<%= j(render partial: 'index') %>")

app/views/home/top.html.erb
<div class="top-wrapper">
  <div class="container">
    <h1>Joberani</h1>
    <p>Joberaniは障害者と働いたことがある人の口コミ共有サイトです。</p>
    <p>一緒に働いたあの人とのエピソードを共有してみませんか？</p>
    <div class="btn-wrapper">
      <% if user_signed_in? %>
        <a href="/posts" class="btn signup">みんなの投稿を見る</a>
      <% else %>
        <a href="/users/sign_up" class="btn signup">新規登録はこちら</a>
      <% end %>
    </div>
  </div>
</div>
<section id= "about">
 <div class="intro-wrapper">
  <div class="container">
    <div class="heading">
      <h2>Joberaniとは？</h2>
    </div>
    <div class="intros">
      <div class="intro">
        <div class="intro-icon">
          <i class="fa fa-info-circle" id="fa-intro"></i>
          <p>Joberaniの意味</p>
        </div>
        <p class="fa fa-circle txt-contents">名前のJoberaniとは英語のJobとマレーシア語のBerani(勇気)を合わせた造語。ジョブラニと発音する。</p>
      </div>
      <div class="intro">
        <div class="intro-icon">
          <i class="fa fa-lightbulb-o" id="fa-intro"></i>
          <p>目的</p>
        </div>
        <p class="fa fa-circle txt-contents">障害者と働いたことがある人がノウハウを共有し、
        これから一緒に働く予定の人や一緒に働いていて接し方がわからず悩んでいる人の手助けになること。</p>
      </div>
      <div class="intro">
        <div class="intro-icon">
          <i class="fa fa-user-plus" id="fa-intro"></i>
          <p>なぜ障害者？</p>
        </div>
        <p class="fa fa-circle txt-contents">人手不足が叫ばれているのに障害者雇用水増し問題が発生した。関わり方を知っていれば障害者の雇用の促進につながるはずだ。</p>
        
      </div>
      <div class="intro">
        <div class="intro-icon">
          <i class="fa fa-check-circle" id="fa-intro"></i>
          <p>設立経緯</p>
        </div>
        <p class=" fa fa-circle txt-contents">私の身内にも障害者がいる。
        関わる機会がある人が「こういう工夫があれば問題なく働ける」ということを共有するため。</p>
      </div>
    </div>
  </div>
 </div>
</section> 
<div class="message-wrapper">
  <div class="container">
    <% if user_signed_in? %>
      <div class="heading">
        <h2>投稿をする</h2>
        <h3>みんなに経験をシェアしませんか？<br>
        あなたの経験が誰かの役に立つかもしれません！
        </h3>
        
      </div>
      <a class="btn message" href="/posts/new">投稿する</a>
      <a class="btn message" href="/posts">投稿一覧を見てみる</a>
    <% else %>
      <div class="heading">
        <h2>無料会員登録</h2>
        <h3>会員登録をすると投稿ができるようになります。<br>
        会員にならなくても投稿一覧は見れます。</h3>
      </div>
      <a class="btn message" href="/users/sign_up">新規登録はこちら</a>
      <a class="btn message" href="/posts">投稿一覧を見てみる</a>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joberani</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
      <div class="container">
        <ul class="header-menus">
          <% if user_signed_in? %>
             <li>
              <a href="/#about">Joberaniとは</a>
             </li>
             <li>
              <%= link_to "マイページ", user_path(current_user.id) %>
             </li>
             <li>
              <%= link_to "投稿一覧", posts_path %>
             </li>
             <li>
              <%= link_to "新規投稿", new_post_path %>
             </li>
             <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
             </li>
          <% else %>
             <li>
              <a href="/#about">Joberaniとは</a>
             </li>
             <li>
              <%= link_to "会員登録", new_user_registration_path %>
             </li>
             <li>
              <%= link_to "ログイン", new_user_session_path %>
             </li>
          <% end %>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer>
        
    </footer>
  </body>
</html>

app/views/posts/_advice.html.erb
<div class="not-under">
  <% posts.each do |post| %>
    <%= link_to post do %>
      <div class ="card">
          <table class="table table-responsive table-sm post-card">
            <tbody>
              <tr>
                <td class="border-top-0" rowspan="2">
                  <% if post.user.image.present? %>
                    <%= image_tag post.user.image %>
                  <% else %>
                    <%= image_tag '/user.png' %>
                  <% end %>
                </td>
                <td class="border-top-0">名前:<%= post.user.name %><br>
                一緒に働いていた期間:<%= post.period %></td>
              </tr>
              <tr>
                <td class="border-top-0"><strong><%= post.content %></strong></td>
              </tr>
            </tbody>
          </table>
          <small><i class="fa fa-star notfavorite-btn"></i>お気に入り！ <%= post.favorites.count %>件　<i class="fa fa-comment fa-fw"></i>コメント <%= post.comments.count %>件</small>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>

  <div class="form">
   <div class="form-body">
       <% @post.errors.full_messages.each do |message| %>
      <div class="form-error">
       <%= message %>
      </div>
      <% end %>
      
      
     <div class="form-group">
      <%= f.label :会社名, class: "label-inline" %> <small class="text-muted">任意で構いません。〇〇を作っている会社などでも大丈夫です</small>
      <%= f.text_field :company, class:'form-control' %>
     </div>
     
     <div class="form-group">
      <%= f.label :業種や職種, class: "label-inline" %> <small class="text-muted">一緒にどんな仕事をしていましたか</small>
      <span class="badge badge-pill badge-danger">必須</span>
      <%= f.text_field :industry, class:'form-control' %>
     </div>
     
     <div class="form-group">
      <%= f.label :一緒に働いていた期間, class: "label-inline" %>  <small class="text-muted">例:1ヵ月、1年など</small>
      <%= f.text_field :period, class:'form-control' %>
     </div>
     
     <div class="form-group">
      <%= f.label :どのような人と一緒に働いていましたか？, class: "label-inline" %>
      <span class="badge badge-pill badge-danger">必須</span>
      <%= f.text_area :content, class:'form-control' %>
     </div>
     
     <div class="form-group">
      <%= f.label :大変だったことや気を付けたことはありますか？, class: "label-inline" %>
      <span class="badge badge-pill badge-danger">必須</span>
      <%= f.text_area :matter, class:'form-control' %>
     </div>
     
     <div class="form-group">
      <%= f.label :これから一緒に働く人向けにアドバイスはありますか？, class: "label-inline" %>
      <span class="badge badge-pill badge-danger">必須</span>
      <%= f.text_area :episode, class:'form-control' %>
     </div>
     
     
    <input type="submit" value="投稿する">
   </div>
  </div>
  
<% end %>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= render 'form', feed: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="body-full">
  <div class="container-fluid index-body">
    <div class="row">
      <!-- 投稿一覧 -->
      <div id="main" class="col-sm-12 col-md-8">
        <div class="main-body">
          <div>
            <h2>投稿一覧</h2>
          </div>
          <% unless @posts.present? %>
            <p>投稿はまだありません。</p>
          <% end %>
          <%= render partial: "advice", locals: {posts: @posts} %>
        </div>
        <!-- 投稿一覧終了 -->
        <%= paginate @posts %>
      </div>
      <!-- お気に入りが多い投稿一覧 -->
      <div id="side" class="col-sm-12 col-md-4">
        <div class="rank-box">
          <div>
          <span class="rank-box-title"><i class="fa fa-star notfavorite-btn"></i>お気に入りランキング</span>
          <p>お気に入り登録が多い投稿が表示されます。</p>
          </div>
          <div class="not-under">
            <% @favorite_ranking.each.with_index(1) do |post, i| %>
              <%= link_to post do %>
                <div class ="rank">
                  <table class="table table-sm rank-card">
                    <tbody>
                      <tr>
                        <td class="border-top-0" rowspan="2">
                          <% if post.user.image.present? %>
                            <%= image_tag post.user.image %>
                          <% else %>
                            <%= image_tag '/user.png' %>
                          <% end %>
                        </td>
                        <td class="border-top-0"><%= i %>位  名前:<%= post.user.name %></td>
                      </tr>
                      <tr>
                        <td class="border-top-0"><strong><%= post.content %></strong></td>
                      </tr>
                    </tbody>
                  </table>
                  <small><i class="fa fa-star notfavorite-btn"></i>お気に入り！ <%= post.favorites.count %>件　<i class="fa fa-comment fa-fw"></i>コメント <%= post.comments.count %>件</small>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <!-- お気に入りが多い投稿一覧終了 -->
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= render 'form', feed: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <table>
          <tr>
            <td><strong>投稿者</strong></td>
          </tr>
          <tr>
            <td colspan="2">
              <div class="pname">
                <%= @user.name %>
              </div>
              <% if @user.image.present? %>
                <%= image_tag @user.image %>
              <% else %>
                <%= image_tag '/user.png' %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><strong>会社名</strong></td>
          </tr>
          <tr>
            <td><%= @post.company %></td>
          </tr>
          <tr>
            <td><strong>業種</strong></td>
          </tr>
          <tr>
            <td><%= @post.industry %></td>
          </tr>
            <td><strong>一緒に働いていた期間</strong></td>
          </tr>
          <tr>
            <td><%= @post.period %></td>
          </tr>
          <tr>
            <td><strong>どのような人と一緒に働いていましたか？</strong></td>
          </tr>
          <tr>
            <td><%= @post.content %></td>
          </tr>
          <tr>
            <td><strong>大変だったことや気を付けたことはありますか？</strong></td>
          </tr>
          <tr>
            <td><%= @post.matter %></td>
          </tr>
          <tr>
            <td><strong>これから一緒に働く人向けにアドバイスはありますか？</strong></td>
          </tr>
          <tr>
            <td><%= @post.episode %></td>
          </tr>
      </table>
      
      <div class="post-time">
        <%= @post.created_at %>
      </div>
      <div class="fav-rank">
        <div id="fav_area">
          <%= render partial: 'favorites/index' %>
        </div>
      </div>
      <% unless current_user == nil %>
        <% if @post.user_id == current_user.id %>
          <div class="post-menus">
            <%= link_to '編集', edit_post_path(@post.id) %>
            <%= link_to '削除', post_path(@post.id),method: :delete, data: { confirm: "削除してよろしいですか？", commit: "削除する", cancel: "やっぱりやめる", title: "ご確認ください" } %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <h4><i class="fa fa-comment fa-fw"></i>コメント</h4>
        <div id="comments_area">
          <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
          <%= render partial: 'comments/index', locals: { comments: @comments } %>
        </div>
      <br>
      <% if user_signed_in? %>
        <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
        <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <br>
    <h2><%= @user.name %> さんのページ</h2>
    <div class="user">
      <table class="table table-striped table-bordered">
        <tr>
          <td colspan="2">
            <% if @user.image.present? %>
              <%= image_tag @user.image %>
            <% else %>
              <%= image_tag '/user.png' %>
            <% end %>
            <div class="sname">
              <%= @user.name %>
            </div>
          </td>
        </tr>
        <tr>
          <td>年齢</td>
          <td><%= @user.age %></td>
        </tr>
        <tr>
          <td>性別</td>
          <td><%= @user.gender %></td>
        </tr>
        <tr>
          <td>出身地</td>
          <td><%= @user.town %></td>
        </tr>
        <tr>
          <td colspan="2">自己紹介</td>
        </tr>
        <tr>
          <td colspan="2"><%= @user.introduce %></td>
        </tr>
      </table>
      <% unless current_user == nil %>
        <% if @user.id == current_user.id %>
          <%= link_to edit_user_registration_path(@user) do %>
          プロフィールを編集
          <% end %>
        <% end %>
      <% end %>
    </div>
    
      <h2><%= @user.name %> さんの投稿一覧</h2>
      <% unless @posts.present? %>
        <p><%= @user.name %> さんの投稿はまだありません。</p>
        <% if current_user.present? %>
          <% if @user.id == current_user.id %>
            <strong><p>投稿してみませんか？ </p></strong><a class="btn message" href="/posts/new">投稿する</a>
          <% end %>  
        <% end %>
      <% end %>
      
      <%= render partial: "posts/advice", locals: {posts: @posts}  %>
    
      <div>
        <h2><%= @user.name %> さんのお気に入り一覧</h2>
        <% unless @favorite_posts.present? %>
          <p><%= @user.name %> さんがお気に入り登録した投稿はまだありません。</p>
        <% else %>
            <%= render partial: "posts/advice", locals: {posts: @favorite_posts}  %>
        <% end %>
      </div>
      <% if current_user.present? %>
        <% if @user.id == current_user.id && @posts.present? %>
          <strong><p>投稿ありがとうございます！他にも投稿しませんか？</p></strong><a class="btn message" href="/posts/new">投稿する</a>
        <% end %>
      <% end %>
  </div>
</div>